version: "3"
services:
  sqlite:
    container_name: lendsqr-container
    image: mysql2:latest
    volumes:
      - mysql2-data:/lendsqr
    ports:
      - "30062:30062"
    restart: always

volumes:
  mysql2-data:
